// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfdZiL7DsgA4atfPdlb7souH6DXJpdHW4',
    appId: '1:527868667064:web:f27aa75d954fbd55acc04d',
    messagingSenderId: '527868667064',
    projectId: 'flutterlms-c2180',
    authDomain: 'flutterlms-c2180.firebaseapp.com',
    storageBucket: 'flutterlms-c2180.firebasestorage.app',
    measurementId: 'G-YYPJ3QJ4GP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_2Ybi5p4TBmkPqDl3oVld6ww-_lBBChw',
    appId: '1:527868667064:android:c800d5565d20fe2bacc04d',
    messagingSenderId: '527868667064',
    projectId: 'flutterlms-c2180',
    storageBucket: 'flutterlms-c2180.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX15yDX1qIk7CWLixuvIPW4lbI5WAmi88',
    appId: '1:527868667064:ios:e5b6ef00f9192405acc04d',
    messagingSenderId: '527868667064',
    projectId: 'flutterlms-c2180',
    storageBucket: 'flutterlms-c2180.firebasestorage.app',
    iosBundleId: 'com.example.learningManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDX15yDX1qIk7CWLixuvIPW4lbI5WAmi88',
    appId: '1:527868667064:ios:e5b6ef00f9192405acc04d',
    messagingSenderId: '527868667064',
    projectId: 'flutterlms-c2180',
    storageBucket: 'flutterlms-c2180.firebasestorage.app',
    iosBundleId: 'com.example.learningManagementSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfdZiL7DsgA4atfPdlb7souH6DXJpdHW4',
    appId: '1:527868667064:web:2bbc9d63e86f9723acc04d',
    messagingSenderId: '527868667064',
    projectId: 'flutterlms-c2180',
    authDomain: 'flutterlms-c2180.firebaseapp.com',
    storageBucket: 'flutterlms-c2180.firebasestorage.app',
    measurementId: 'G-B59S4MZX3G',
  );
}
